In [14]:
import numpy as np
a = np.random.randint(1,101,size =(5,5))
print(a)

[[34 83 38 34 12]
 [87 95 18 21 28]
 [40 12 48 63 25]
 [43 90 15 10 95]
 [14 96 95 34 82]]


In [15]:
mid = a[2,2]
print(mid)

48


In [16]:
np.mean(a, axis=1)

array([40.2, 49.8, 37.6, 50.6, 64.2])

In [17]:
mean = np.mean(a)
b = a[a>mean]
print(b)

[83 87 95 63 90 95 96 95 82]


In [19]:
def spiral(matrix):
    s = []
    top, bot = 0, matrix.shape[0] - 1
    left, right = 0, matrix.shape[1] - 1

    while top <= bot and left <= right:
        for i in range(left, right + 1):
            s.append(int(matrix[top, i]))
        top += 1

        for i in range(top, bot + 1):
            s.append(int(matrix[i, right]))
        right -= 1

        if top <= bot:
            for i in range(right, left - 1, -1):
                s.append(int(matrix[bot, i]))
            bot -= 1

        if left <= right:
            for i in range(bot, top - 1, -1):
                s.append(int(matrix[i, left]))
            left += 1

    return s

print(spiral(a))


[34, 83, 38, 34, 12, 28, 25, 95, 82, 34, 95, 96, 14, 43, 40, 87, 95, 18, 21, 63, 10, 15, 90, 12, 48]
